# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (28 is current forge version)

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/thraaawn/BonsaiTrees/issues/" #optional
license="MIT"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="bonsaitrees2" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName="Bonsai Trees 2" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional

# A text field displayed in the mod UI
authors="Davenonymous" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Bonsai Pots allows growing trees in small spaces.
'''



# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bonsaitrees2]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory

    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.bonsaitrees2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bonsaitrees2]]
    modId="libnonymous"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
